# AR parameters such as FFT parameters.
audio_repr: ar_ajepa.AR_AJEPA
weight_file: external/ajepa/outputs/xps/c05cb37f/jepa-ep95.pth.tar
feature_d: 2048
sample_rate: 16000
crop_size:
  - 128
  - 160
n_fft: 1024
win_length: 1024
hop_length: 512  # with a patch of 16x16 and sr = 16000, actual time length of patch is exactly hop_length ms
n_mels: 128
f_min: 50
f_max: 8000
patch_size: 16
model_name: "vit_base"
temporal_pooling_type: mean
postnorm: dataset

# Training parameters.
batch_size: 256
lr_lineareval: 0.0003
report_per_epochs: 20
early_stop_epochs: 20

# Fine-tuning parameters.
## CAUTION: The following parameters not confirmed to work. ##
warmup_epochs: 5
mixup: 0.5
ft_bs: 256
ft_lr: 0.001
ft_early_stop_epochs: -1 # -1: no early stopping
ft_epochs: 200
ft_freq_mask: 30
ft_time_mask: 100
ft_rrc: True
